In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
lst = [1,2,3,4]
print(lst)
print(type(lst))

[1, 2, 3, 4]
<class 'list'>


In [4]:
lst = [[1,2,3],[4,5,6]]
print(lst)

[[1, 2, 3], [4, 5, 6]]


In [12]:
%timeit [j**4 for j in range(1,9)]

1.04 µs ± 26 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [13]:
%timeit np.arange(1,9)**4

2.52 µs ± 199 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [17]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [20]:
l = []
for i in range(1,5):
    input_ = int(input("enter number"))
    l.append(input_)
    
arr = np.array(l)
print(arr)
print(arr.ndim)

enter number1
enter number2
enter number3
enter number3
[1 2 3 3]
1


In [28]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [32]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [37]:
arr10 = np.array([1,2,3],ndmin=10)
print(arr10)
print(arr10.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]]
10


In [38]:
z = np.zeros(3)
print(z)

[0. 0. 0.]


In [41]:
z1 = np.zeros((3,4))
print(z1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
o = np.ones(4)
print(o)

[1. 1. 1. 1.]


In [44]:
o1 = np.ones(((3,2,2)))
print(o1)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [45]:
e = np.empty(4)
print(e)

[1. 1. 1. 1.]


In [48]:
r = np.arange(1,10,2)
print(r)

[1 3 5 7 9]


In [55]:
d = np.eye(3)
print(d)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [59]:
ls = np.linspace(0,10,num =4)
print(ls)

[ 0.          3.33333333  6.66666667 10.        ]


In [65]:
ran = np.random.rand(4)
print(ran)

[0.33082785 0.29444001 0.66227467 0.1911706 ]


In [66]:
ran1 = np.random.rand(2,4)
print(ran1)

[[0.40469983 0.4974173  0.21828203 0.82182155]
 [0.91929163 0.40527957 0.31887134 0.9520483 ]]


In [67]:
# randn gives positive and negative both with close to zero
x = np.random.randn(3)
print(x)

[0.57627227 1.79186052 0.57790956]


In [69]:
y = np.random.ranf(3)
print(y)

[0.73710927 0.9176322  0.02413014]


In [82]:
z = np.random.randint(1,100,4)
print(z)
print(type(z))

[58 71 10 73]
<class 'numpy.ndarray'>


In [84]:
arr = np.array([1.1,2.1,3.0])
print(arr.dtype)

float64


In [85]:
str1 = np.array(["a","b","c"])
print(str1.dtype)

<U1


In [86]:
mix = np.array(["1","a","c",1,2,3])
print(mix.dtype)

<U11


In [9]:
import numpy as np
x = np.array([1,2,3],dtype = np.float64)
print(x.dtype)
print(x)

y = np.array([1,2,3],dtype = "S")
print(y)
print(y.dtype)

new_x = x.astype("f")
print(new_x)

float64
[1. 2. 3.]
[b'1' b'2' b'3']
|S1
[1. 2. 3.]


In [18]:
#Arithmetic Operators

var = np.array([1,2,3,4])
var_add = var + 3
print(var_add)

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

# sum_arr = arr1 + arr2
sum_arr = np.add(arr1,arr2)
diff_arr = np.subtract(arr1,arr2)


print(sum_arr)
print(diff_arr)




[4 5 6 7]
[ 6  8 10 12]
[-4 -4 -4 -4]


In [19]:
arr2d1 = np.array([[1,2,3],[1,2,3]])
arr2d2 = np.array([[1,2,3],[1,2,3]])

sum_2d = arr2d1 +arr2d2
print(sum_2d)

[[2 4 6]
 [2 4 6]]


In [25]:
arr1 = np.array([1,2,3,4])
print(np.min(arr1))
print(np.max(arr1))
print(np.argmin(arr1))
print(np.argmax(arr1))
print(np.sqrt(arr1))
print(np.sin(arr1))
print(np.cos(arr1))
print(np.cumsum(arr1))

1
4
0
3
[1.         1.41421356 1.73205081 2.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1  3  6 10]


In [38]:
#Shape and Reshape

import numpy as np

#shape
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print()
print(arr.shape)

arr2 = np.array([1,2,3,4],ndmin=5)
print(arr2)
print(arr2.shape)

#reshape
arr = np.array([1,2,3,4,5,6])
x = arr.reshape(1,3,2)
print(x)
print(x.ndim)

one = x.reshape(-1)
print(one)
print(one.ndim)




[[1 2 3]
 [4 5 6]]

(2, 3)
[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)
[[[1 2]
  [3 4]
  [5 6]]]
3
[1 2 3 4 5 6]
1


In [3]:
# Broadcasting

import numpy as np

# arr1 = np.array([1,2,3])
# arr2 = np.array([1,2,3,4])
# print(arr1+arr2)

arr1 = np.array([1,2,3])
arr2 = np.array([[1],[2],[3]])
print(arr1)
print(arr2)

add = arr1 + arr2
print(add)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [14]:
# Indexing and Slicing

arr1 = np.array([1,2,3])
print(arr1[1])

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[0,2])

arr3 = np.array([[[1,2],[4,5]]])
print(arr3[0,1,1])

arr4 = np.array([1,2,3,4,5,6])
print(arr4[1:5])
print(arr4[1:])
print(arr4[:5])
print(arr4[::2])
print(arr4[::-1])

arr5 = np.array([[1,2,3],[4,5,6]])
print(arr5[1,0:])

2
3
5
[2 3 4 5]
[2 3 4 5 6]
[1 2 3 4 5]
[1 3 5]
[6 5 4 3 2 1]
[4 5 6]


In [21]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

for i in arr1:
    print(i)
    
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

for i in arr2:
    for j in i:
        print(j)
    
arr3 = np.array([[[1,2,3],[4,5,6]]])
print(arr3)

for i in np.nditer(arr3):
    print(i)
    
for i,d in np.ndenumerate(arr3):
    print(i,d)

[1 2 3 4 5 6]
1
2
3
4
5
6
[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6
[[[1 2 3]
  [4 5 6]]]
1
2
3
4
5
6
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6


In [26]:
# Copy and View 

arr = np.array([1,2,3])
arr_copy = arr.copy()
print(arr)
print(arr_copy)

arr[0] = 11
print(arr_copy)

arr_view = arr.view()
print(arr)
print(arr_view)

[1 2 3]
[1 2 3]
[1 2 3]
[11  2  3]
[11  2  3]


In [34]:
# Joining and Split
# arr1 = np.array([1,2,3])
# arr2 = np.array([4,5,6])

# new_arr = np.concatenate((arr1,arr2))
# print(new_arr)

# arr1 = np.array([[1,2,3],[8,9,10]])
# arr2 = np.array([[4,5,6],[11,12,13]])
# new_arr = np.concatenate((arr1,arr2),axis = 1)
# print(new_arr)


# arr1 = np.array([1,2,3])
# arr2 = np.array([4,5,6])
# new_stack = np.stack((arr1,arr2),axis=0)
# new_stack1 = np.hstack((arr1,arr2))
# new_stack2 = np.vstack((arr1,arr2))
# new_stack3 = np.dstack((arr1,arr2))


# print(new_stack)
# print(new_stack1)
# print(new_stack2)
# print(new_stack3)


arr1 = np.array([1,2,3,4,5,6])
print(arr1)

new_arr = np.split(arr1,3)
print(new_arr)

arr2 = np.array([[1,2],[3,4],[5,6]])
new_arr = np.split(arr2,3)
print(new_arr)


[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [38]:
# numpy functions - search, sort, filter
arr1 = np.array([1,2,3,4,5,6,2,1,3,4])
x = np.where(arr1==2)
print(x)

y = np.where(arr1//2==2)
print(y)

arr2 = np.array([1,2,3,4,5,6,2,1,3,4])
print(np.sort(arr2))


(array([1, 6], dtype=int64),)
(array([3, 4, 9], dtype=int64),)
[1 1 2 2 3 3 4 4 5 6]


In [46]:
arr1 = np.array([1,2,3,4,5,6])
np.random.shuffle(arr1)
print(arr1)

arr2 = np.array([1,2,3,4,5,6,2,1,3,4])
x = np.unique(arr2,return_index=True,return_counts=True)
print(x)

arr3 = np.array([1,2,3,4,5,6])
y = np.resize(arr3,(2,3))
print(y)






[2 3 4 1 6 5]
(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 5], dtype=int64), array([2, 2, 2, 2, 1, 1], dtype=int64))
[[1 2 3]
 [4 5 6]]


In [57]:
arr1 = np.array([1,2,3,4,5,6])
new = np.insert(arr1,(1,5),10)
print(new)

arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
new = np.insert(arr1,2,10,axis=0)
print(new)

arr1 = np.array([1,2,3,4,5,6])
y = np.append(arr1,9)
print(y)

z = np.delete(arr1,2)
print(z)


[ 1 10  2  3  4  5 10  6]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [10 10 10]]
[1 2 3 4 5 6 9]
[1 2 4 5 6]


In [62]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print(type(arr1))

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

mul = np.multiply(arr1,arr2)
print(mul)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [65]:
mat1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(mat1)
print(type(mat1))

mat2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
mul = mat1.dot(mat2)
print(mul)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
